name: Build and Run Egg Timer

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up C Compiler
      run: sudo apt-get install build-essential

    - name: Compile C Program
      run: gcc timer.c -o timer

    - name: Run the C Program
      run: ./timer
